export const INCREMENT_COUNTER ="NCREMENT_COUNTER"
export const DECREMENT_COUNTER ="DECREEMENT_COUNTER"


export const GET_DOCTORS="GET_DOCTORS"
export const ADD_DOCTORS="ADD_DOCTORS"
export const DELETE_DOCTORS="DELETE_DOCTORS"
export const UPDATE_DOCTORS="UPDATE_DOCTORS"

export const GET_MEDICINE="GET_MEDICINE"

export const ADD_TO_CART="ADD_TO_CART"
export const INC_QTY="INC_QTY"
export const DEC_QTY="DEC_QTY"
export const REMOVE_ITEM="REMOVE_ITEM"