export const INCREMENT_COUNTER ="NCREMENT_COUNTER"
export const DECREMENT_COUNTER ="DECREEMENT_COUNTER"


export const GET_DOCTORS="GET_DOCTORS"
export const ADD_DOCTORS="ADD_DOCTORS"
export const DELETE_DOCTORS="DELETE_DOCTORS"
export const UPDATE_DOCTORS="UPDATE_DOCTORS"